package model.json;

/**
 * Bean to store generic data generated by a sensor.
 * Created by Mathieu on 23/01/2015.
 */
public class Data {
    /**
     * The timestamp at which the measure has been taken.
     */
    public int timestamp;
    /**
     * A label concerning data collected.
     */
    public String label;
    /**
     * A numeric representation of the collected data.
     */
    public double value;
    /**
     * A string identifying the mote that made this mesure.
     */
    public String mote;

    /**
     * Returns the timestamp of the measure.
     * @return measure's timestamp.
     */
    public int getTimestamp() {
        return timestamp;
    }

    /**
     * Changes measure's timestamp.
     * @param timestamp the new timestamp.
     */
    public void setTimestamp(int timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns the measure's associated label.
     * @return the associated label.
     */
    public String getLabel() {
        return label;
    }

    /**
     * Changes the measure's associated label.
     * @param label the new label.
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * Returns the measure's numerical value.
     * @return the numerical value.
     */
    public double getValue() {
        return value;
    }

    /**
     * Changes the measure's numerical value.
     * @param value the new value.
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Returns the string identifying the mote which has taken the measure.
     * @return the string identifying the mote.
     */
    public String getMote() {
        return mote;
    }

    /**
     * Changes the string identifying the mote which has taken the measure.
     * @param mote the new string.
     */
    public void setMote(String mote) {
        this.mote = mote;
    }
}
